-- Create the searches table
create table searches (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  search_type text,
  from_location text,
  to_location text,
  departure_date date,
  return_date date,
  adults integer,
  children integer,
  class text,
  company_name text,
  rooms integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table searches enable row level security;

-- Policies for searches table
create policy "Users can insert their own searches."
on searches for insert to authenticated with check ( auth.uid() = user_id );

create policy "Users can view their own searches."
on searches for select to authenticated using ( auth.uid() = user_id );

-- Create indexes
create index idx_searches_user_id on searches(user_id);
